apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-8irt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-8irt
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-8irt
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-8irt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-8irt
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/happy-path-efhp-tenant/appstudio/dc-metro-map-8irt@sha256:40a712890a618a64b4d659e8ca25831a6b7063d69b0a96a5a928b83dcbcb6c5e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
